library(sf)
library(GWmodel3, lib.loc = "../../../Rlibrary.tmp")
library(Rmpi)
# data(LondonHP)
# gwr_basic(PURCHASE~FLOORSZ+UNEMPLOY, LondonHP, 64, TRUE, verbose = 2)
data(wuhan.hp, package = "hgwrr")
gwr_multiscale(Price ~ d.PrimarySchool + BuildingArea + Fee, wuhan.hp, config = list(mgwr_config(adaptive = T)), optim_bw_range = c(256, Inf))
invisible(mpi.finalize())