# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.c_gwr_basic <- function(
    x, y, coords, indep_vars, dep_var,
    bw, adaptive, kernel, longlat, p, theta,
    hatmatrix, parallel_type, parallel_arg
) {
    .Call("_GWmodel_gwr_basic",
        x, y, coords, indep_vars, dep_var,
        bw, adaptive, kernel, longlat, p, theta,
        hatmatrix, parallel_type, parallel_arg
    )
}
