name: R Package CRAN Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  check_windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          choco install pandoc
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          rtools-version: '42'
          update-rtools: true
      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::roxygen2
          needs: check
      - name: Check Package
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          build_args: 'c("--no-manual", "--resave-data")'
          error-on: '"error"'
          check-dir: '"check"'

  check_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Install Dependencies
        run: brew install gsl pandoc
      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::roxygen2
          needs: check
      - name: Check Package
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          build_args: 'c("--no-manual", "--resave-data")'
          error-on: '"error"'
          check-dir: '"check"'
  
  check_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian, fedora]
        version: [release, devel]
      fail-fast: false
    container:
      image: ghcr.io/gwmodel-lab/gwmodel3-test-${{ matrix.os }}-${{ matrix.version }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build and Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          build_args: 'c("--no-manual", "--resave-data")'
          error-on: '"error"'
          check-dir: '"check"'
