name: Build and Publish to GitHub Release

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag name to create release"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gwmodel-lab/gwmodel3-test-debian-release:latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build R Package
        run: R CMD build .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: GWmodel3_*.tar.gz
          draft: true
          name: ${{ github.event_name == 'worflow_dispatch' && inputs.tag || github.ref_name }}
          tag_name: ${{ github.event_name == 'worflow_dispatch' && inputs.tag || github.ref_name }}
           
        
